### ISSUE TITLE
Publish to melpa stable

### ISSUE THREAD

**Issue by SerialVelocity** [benma/go-dlv.el#11]
A lot of people pull in [melpa stable](https://stable.melpa.org) instead of melpa as it is usually much more stable. Any change you could publish a release there?

**Comment by benma** [comment]
I am not very familiar with Melpa Stable. I tagged the current release, please let me know if that worked.

**Comment by SerialVelocity** [comment]
Looks like it now exists here:
https://stable.melpa.org/#/go-dlv

Thanks!
