### ISSUE TITLE
Tutorials and Docs for go-dlv

### ISSUE THREAD

**Issue by andyafter** [benma/go-dlv.el#12]
Hi is there any tutorials for this repo? Really need to use it.

**Comment by benma** [comment]
First, delve needs to be installed: https://github.com/derekparker/delve/

dlv is a GUD-based debugger:

https://www.gnu.org/software/emacs/manual/html_node/emacs/Commands-of-GUD.html

After loading go-dlv, just call `M-x dlv` or `M-x dlv-current-func` to get started.

Pull requests for tutorials and documentation is very welcome.
