### ISSUE TITLE
Sources not displayed on breakpoints

### ISSUE THREAD

**Issue by spremel** [benma/go-dlv.el#15]
Hi,

Looking for a simple front debugger for Go, I came accross this one. Works well, except the sources are not displayed when stepping on a line with a breakpoint set.

It turns out the file/line regex does not work in some circumstances:
https://github.com/benma/go-dlv.el/blob/45a9e8a047c9995eb7c802268d96b3e527569f41/go-dlv.el#L46
 
```
> main.main() ./hello.go:8 (hits goroutine(1):1 total:1) (PC: 0x49c398) => KO
> main.main() ./hello.go:9 (PC: 0x49c3af) => OK
```

The following seems to work (not much changes.. just turned off the greediness of the first group):
`"^> .+(.*) \\(.+?\\)\\:\\([0-9]+\\).*?$"`

Delve Debugger
Version: 1.1.0
Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $

Thanks

**Comment by benma** [comment]
Thanks. Seems to be fixed by https://github.com/benma/go-dlv.el/pull/16
