### ISSUE TITLE
A new function to quickly debug current test

### ISSUE THREAD

**Issue by kostya-sh** [benma/go-dlv.el#2]
I wrote a simple function to launch delve with the current test and find it extremely useful:

```
(defun my-go-debug-current-test ()
  "Debug current test with dlv"
  (interactive)
  (let ((test-name (go-test-get-current-test))
        (gud-buffer (get-buffer "*gud-test*")))
    (when test-name
      (when gud-buffer (kill-buffer gud-buffer))
      (dlv (s-concat go-dlv-command-name " test -- -test.run " test-name))
      (gud-call (s-concat "break " test-name))
      (gud-call "continue"))))
```

If you think this function would be good addition to the go-dlv.el I will create a pull request.

**Comment by benma** [comment]
Looks interesting, thanks. 

I am definitely open to adding such functionality to the package. Please do create a PR, but I can only review it in a couple of weeks, as I am still traveling.
