### ISSUE TITLE
no "breakpoint" indication in fringe

### ISSUE THREAD

**Issue by phtrivier** [benma/go-dlv.el#7]
I'm new to GUD, so it might not be a go-dlv issue. 

I managed to start  dlv to debug a running program. 
I can add breakpoints from a source file with `M-x gud-break`

When I run the program and hit the breakpoint, I see a fringe marker (a yellow arrow in my case) next to the current line in my source buffer. 
From what I read, I was expecting to also see a fringe marker(a red dot ?) in the source file (so that I now where the breakpoints are) ; I do not see anything. 

Possibly related : when running the `list` command from dlv, I get a "no source available" result : 

```
Breakpoint 1 set at 0x511ea3 for xyz.go:69
(dlv) list
Stopped at: 0x7f2abedf6cd0
=>no source available
```

Any idea what I should investigate ? 

Thanks

**Comment by benma** [comment]
Apparently, someone else posted the same question on SO: http://emacs.stackexchange.com/questions/16463/gud-highlight-breakpoints-with-custom-debugger.

go-dlv is indeed only a thin layer on top of the gud library, so UI questions should be directed there. To be honest, I am not sure if gud shows breakpoints like that usually, or supports that. 

 About the second issue: I will try to reproduce that soon, but am a bit short on time right now.

**Comment by benma** [comment]
Found some time :laughing: I tried reproducing it but could not, `list` seems to work fine here. Please try the latest `master` and re-open if this is still an issue.
