### ISSUE TITLE
direct to headless server

### ISSUE THREAD

**Issue by christopherreay** [benma/go-dlv.el#9]
How much work would it be to have an emacs plugin that used rpc to connect with a headless dlv server?

Which components in the dlv stack are useful?

**Comment by christopherreay** [comment]
would it be possible, for example, to replace the dlv program that emacs expects, with some thing that converts the requests to rpc format?

**Comment by benma** [comment]
Yes, you can configure which command should be called, and build remote support this way.

Maybe the job could be made easy with ssh (with tmux?) to tunnel the commands, but I'm not sure about that.
